services:
    # Repository
    asmodine.admin.repository.physical_profile:
        class: Asmodine\CustomerBundle\Repository\PhysicalProfileRepository
        arguments: ['@doctrine.dbal.default_connection']
